name: Ruff
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
      - run: "check --fix --exclude tests/ --exclude generate_docs.py ."
      - run: "format --check --diff"
          
